language: node_js
node_js:
  - "12"
  - "10"
  - "8"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
scripts:
  - npm run bootstrap
  - npm run coveralls
  - npm run bundle
