name: Release

on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Retrieve dependencies from cache
        id: cacheNpm
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: npm-v14-${{ runner.os }}-refs/heads/master-${{ hashFiles('package.json') }}
          restore-keys: npm-v14-${{ runner.os }}-refs/heads/master-

      - name: Install dependencies
        if: steps.cacheNpm.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Bootstrap project
        run: |
          npm run bootstrap
      - name: Running codecov
        run: npm run codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Configure CI Git User
        run: |
          git remote rm origin
          git remote add origin "https://$USER_NAME:$GH_TOKEN@github.com/$USER_NAME/ygkit.git"
          git fetch
          git config --global user.email octobot@github.com
          git config --global user.name GitHub Actions
        env:
          USER_NAME: yugasun
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Releasing
        run: |
          npm run build
          npm run release:ci
        env:
          USER_NAME: yugasun
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: yugasun
          GIT_AUTHOR_EMAIL: yugasun.bj@gmail.com
          GIT_COMMITTER_NAME: yugasun
          GIT_COMMITTER_EMAIL: yugasun.bj@gmail.com
